name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md' 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with nunit
      run: dotnet test --verbosity normal

    - name: Remove File
      run: Remove-Item –path ./SpineEngine/obj –recurse

    - name: Restore packages with nuget
      run: msbuild ./SpineEngine/SpineEngine-BridgeNet.csproj /restore /property:Configuration=Release

    - name: Build with msbuild
      run: msbuild ./SpineEngine/SpineEngine-BridgeNet.csproj /property:Configuration=Release
